### ISSUE TITLE
搭建后出现"403"报错

### ISSUE THREAD

**Issue by KaRuichin** [nyancatda/mcserverweb-golang#1]
http://mcs.achley.online:27001/
![image](https://user-images.githubusercontent.com/69111766/148977766-e46a3271-ed57-4f2e-adc1-93fda87ddad0.png)
![image](https://user-images.githubusercontent.com/69111766/148977013-afddfb04-224c-44a8-9617-e8e692aa5bc2.png)

曾经用过大佬的项目 (https://github.com/nyancatda/mcserverweb) 搭建成功过，如今回坑再次尝试却报错了...
尝试过重启nginx
环境：Windows Server 2022 Datacenter,nginx-1.21,php-8.0
如需提供其他信息请提出。

以上

**Comment by nyancatda** [comment]
新版本使用golang制作了，而不是php，你可以直接下载发行版本启动即可，如果需要使用域名请使用nginx进行反向代理

**Comment by KaRuichin** [comment]
明白，感谢回复。
